# Generated by Django 4.1 on 2022-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_details_remove_drop_branch_remove_drop_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cheque',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='credit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='debit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='female',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='male',
            field=models.BooleanField(),
        ),
    ]
