# Generated by Django 4.1 on 2022-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_details_cheque_alter_details_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cheque',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='details',
            name='credit',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='details',
            name='debit',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='details',
            name='female',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='details',
            name='male',
            field=models.BooleanField(default=None),
        ),
    ]
